

{

    $srcImageURL = "https://SourceSotrageAccount.blob.core.windows.net/system/Microsoft.Compute/Images/spserver2016image/"
    $srcImageKey = "longsourcekey=="

    $destImageURL = "https://DesintationStorageAccount.blob.core.windows.net/vm-images"
    $destImageKey = "longdestinationkey=="
    
    $imageFileName = 'SpServer2016-osDisk.7b42e068-d2b0-479a-9d1c-e512af27e68c.vhd'


    # Contatonate AzCopy command
    $azCopyCmd = "AzCopy /Source:" + $srcImageURL + " /Dest:" + $destImageURL + " /SourceKey:" + $srcImageKey + " /DestKey:" + $destImageKey + " /s /pattern:" + $imageFileName
    
    # Paste into the Azure Storage Command Console    
    $azCopyCmd

    # Below is an AZCopy command generated by this section.
    # -----------------------------------------------------
    # AzCopy /Source:https://vmimagevhds.blob.core.windows.net/spservers/ /Dest:https://timomainstore6546546.blob.core.windows.net/vm-images /SourceKey:PwWZw9lprzfcmwznN4VgDyZVkrTntqIgDNacbMewlYyk6pLUIrZOeVbSw+E8yTW9/vK+CBZjK9w+F1ma74YCxg== /DestKey:uUY4pDKgkR5buEK9tvAtLm0LsGCHNFAbIMDXvdg9QkkU/jYrl1Y+Kv0H4CIfzxAkUx6tdvjiT/Igp0BipnBBPg== /s /pattern:SpServer2016-osDisk.0e9267eb-fec1-4b56-a0f2-5c5fc5dee1c7.vhd
    #
}